### ISSUE TITLE
Discuss with team: should I/we remove the project or schedule it as project hours?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#100]
Discuss with team: should I/we remove the project or schedule it as project hours?

RB: I volunteer to schedule some of my hours as project hours

##### What stopped us from learning (What held us back)

- A: A very fast pace, at times there was too much info to absord (ie unit testing)
- Having to juggle both doing something for the project and also focusing on the exercises at the same time
- A: Lack of time to complete the exercises.
- A:Not knowing form the start exactly what to do during the exercises
- A: Little time to work on exercises after understanding all the info
- A: Laggy teaching video
- A: From simple example to applying it to project design in a short period of time is quiet challenging. 
- A: Not knowing where to find certain things (kambam board, the correct learners folder etc)
- A: Not knowing from where to start and to where to go
- A: Not enough time for the exercises, not knowing the time limit for the exercises.
- A: Teaching video not working properly, wasn't able to see the code properly because of this. 

##### What could we do to improve learning (What can we invent)

- A: Give more time to absorb information before having to apply it on a big project
- A: Either focus on simpler exercises and learning or focus on project work
- A: More clear tasks
- A: Focusing on less topics and working on those more deeply and with more time
- A: take into account the time that these feedback sessions need (second day that the last exercise session is cut short)
- A: In the teaching video show both the code and where it is being copied from, for clarity
- A: Give more time 
- A: Maybe more time or simpler(focused) exercises.
- A:
- A: Tell us how much time we have for completing all exercises. Helps us to not spend too much time on just one of the exercises and then the time is up without us knowing.

**Comment by bclaremar** [comment]
Aren't the project work done as most of the exercises?

**Comment by richelbilderbeek** [comment]
Some exercises indeed work on the learners' project. I still struggle with how to do this well...

I close this issue now, until I have some more clear ideas on this. Thanks Björn for the input!
