### ISSUE TITLE
Implement the project as a package: using python/python3 

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/programming_formalisms#108]
using python3 in scripts may break locally as you mentioned

how to solve that it works for everyone?

If they followed the anaconda installation of python they will get python. 
My python3 point to another installation

Best way may be to check which python will work for them

**Comment by bclaremar** [comment]
Well, making the installation instructions on Friday (Deployment) one can go from a installation scripts to the manual `python[3] -m pip install . [--break-system-packages]`

**Comment by bclaremar** [comment]
Another question.

Will they be needing external packages, like numpy and such?

**Comment by richelbilderbeek** [comment]
Ah, the learners have added requirements :-) . It seems to cause no problem with the build on the main branch though according to [this CI log](https://github.com/programming-formalisms/programming_formalisms_project_autumn_2024/actions/runs/11955494897)
