### ISSUE TITLE
CI or Making package?

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/programming_formalisms#109]
Schedule says: CI at 15, whereas Thursday link goes to Implement as package.

I am guessing that you will leave out packing this time. That will affect my teaching though on Friday!

Perhaps I can try to cover package part as part of deploy?

**Comment by bclaremar** [comment]
Oh, it is in the Friday morning!

thank you!

**Comment by richelbilderbeek** [comment]
Yup, I make sure we implement the package, you can count on that :+1:
