### ISSUE TITLE
Suggest: simplify intake form

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#118]
I took a closer look at the intake form. Do we want to keep it as it is? If not, how to change it?

**Comment by richelbilderbeek** [comment]
I feel it is not worth to bother the learners with things that are not essential. 

From that perspective, I conclude this table:

Column                                                        |Verdict
--------------------------------------------------------------|------------
Timestamp                                                     |Automatic, hence keep
Your name                                                     |Vital
Your email                                                    |Vital
Affiliation                                                   |Not worth it
Which scripting and programming languages do you use?         |Not worth it
Briefly describe your background and experience in programming|Not worth it
What do you expect to learn from this course?                 |Not worth it
How did you learn about this course?                          |Not worth it
Do you plan to follow the entire course?                      |Not worth it
Email address                                                 |Duplicate

I suggest to keep only the name and email, as I feel we should bother our learners with things that are not essential.

However, NBIS may consider more data to be vital. Taking that into account as good as I can, I think:

Column                                                        |Verdict
--------------------------------------------------------------|------------
Timestamp                                                     |Automatic, hence keep
Your name                                                     |Vital
Your email                                                    |Vital
Affiliation                                                   |Worth for NBIS
Which scripting and programming languages do you use?         |Not worth it
Briefly describe your background and experience in programming|Not worth it
What do you expect to learn from this course?                 |Not worth it
How did you learn about this course?                          |Worth for NBIS
Do you plan to follow the entire course?                      |Not worth it
Email address                                                 |Duplicate

I am up for either table. Let's suggest more, then vote :+1:

**Comment by QuantumTwitch** [comment]
I like the lower more simplified one, but trim the Not worth it. We can ask one or to of them as a icebreaker

**Comment by QuantumTwitch** [comment]
I will fix the form as soon as everyone has commented.

**Comment by richelbilderbeek** [comment]
I put the current intake for at https://github.com/UPPMAX/programming_formalisms/blob/main/emails/intake_form.md , with a reference back to this issue :+1:

**Comment by bclaremar** [comment]
Good!

**Comment by richelbilderbeek** [comment]
That means, this is done :+1:
