### ISSUE TITLE
Suggest vote: conformize folder naming 

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#12]
Currently, when doing `ls`, I see:

```
[...]
common-practices
data_structures
DevelopmentDesign
Formalism.png
learning_line.md
[...]
```

Note the mix of naming styles, with `dash-case`, `snake_case`, `CamelCase` and `Titlecase`.

I suggest to follow the current most popular one, which is `snake_case`, which would result in:

```
[...]
common_practices
data_structures
development_design
formalism.png
learning_line.md
[...]
```

I suggest to vote on this :+1:

**Comment by richelbilderbeek** [comment]
Vote from @LarsEklund is on `camel_case`:


> Yes we should harmonize the structure, I of course tend to be old-school (Harking back to the chemist Berzelius 1831) and prefer CamelCase (old programming references) but since that is not preserved when moving through file systems the snake_ case  seem best.

**Comment by bclaremar** [comment]
snake case then?

**Comment by richelbilderbeek** [comment]
3x snake_case, zero votes for anything else. I guess that makes it snake_case :-)

**Comment by richelbilderbeek** [comment]
Will rename at #13  , this is done!
