### ISSUE TITLE
Suggest: put evalations in course menu, under 'Misc'

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#122]
Currently, the evaluations are not reachable from the course's fancy website.

I suggest to make it easily reachable: it would make us more transparent.

What about we vote?

**Comment by richelbilderbeek** [comment]
I vote yes!

**Comment by richelbilderbeek** [comment]
Two out three say yes: let's do it!

**Comment by bclaremar** [comment]
Fine!

Who does it?

**Comment by bclaremar** [comment]
Ah, sorry, I see it!
