### ISSUE TITLE
Join the Programming Formalisms Autumn 2024 team

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#37]
Share your GitHub username here and we'll add you to the team :-)

This is needed to work on the learners' project at https://github.com/programming-formalisms/programming_formalisms_project_summer_2024 :+1:

**Comment by richelbilderbeek** [comment]
richelbilderbeek

**Comment by AitorAldama** [comment]
AitorAldama

**Comment by Jinlinghuang** [comment]
Jinlinghuang

**Comment by monikaBrandt** [comment]
monikaBrandt

**Comment by hykim-5** [comment]
hykim-5

**Comment by Taratype0** [comment]
Taratype0

**Comment by JennyHaggstrom** [comment]
JennyHaggstrom

**Comment by Jarinafsana** [comment]
Jarinafsana

**Comment by CFB2018** [comment]
CFB2018

**Comment by richelbilderbeek** [comment]
Added all learners above to the team. You've received an invite in your email. You will need to accept the invite :-)

**Comment by fabiopohl** [comment]
fabiopohl

**Comment by phuongcaothingoc** [comment]
phuongcaothingoc

**Comment by CeciliaCasadei** [comment]
CeciliaCasadei

**Comment by richelbilderbeek** [comment]
Course is over, well done!

**Comment by richelbilderbeek** [comment]
New course! You can join here :-)

**Comment by CFB2018** [comment]
Hi Richel, is this the same course as before, or is it a continuation of the previous one?

**Comment by richelbilderbeek** [comment]
Hi @CFB2018, this is a new iteration.

Aha, now I understand: you've gotten a message from an Issue! I will close this one :-)
