### ISSUE TITLE
[VOTED] Use `git switch`

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#40]
Currently, we teach both `git checkout` or `git switch`

I think we should minimize the number of git commands.

To do so, we should decide upon using `git checkout` or `git switch`.

Without any research, yet the unconfirmed info that `git switch` is more specific to branching, combined with that we only use these git commands for branching, I'd prefer `git switch` slightly. 

Let's vote on this :+1:

**Comment by richelbilderbeek** [comment]
Changed my opinion: I think we should use `git checkout`, due to a learner not being able to use `git switch` as he had an older version of git.

**Comment by richelbilderbeek** [comment]
I put `git checkout` in my suggested schedule at <https://github.com/UPPMAX/programming_formalisms/tree/main/lesson_plans/2024_autumn#suggested-new-schedule>

**Comment by bclaremar** [comment]
In our prereqs: Version >= 2.28 would do

That will solve compatibility issues with git switch

overview: https://kodekloud.com/blog/git-switch-vs-checkout/

**Comment by richelbilderbeek** [comment]
So, would you vote `git checkout` or `git switch`?

**Comment by bclaremar** [comment]
Björn votes for `git switch`

**Comment by richelbilderbeek** [comment]
Then @LarsEklund will have the deciding vote :-)

**Comment by richelbilderbeek** [comment]
@LarsEklund votes for `git switch` as it is in the prereqs, hence use it. We assume now that this is the preferred method, hence we use `git switch`

**Comment by richelbilderbeek** [comment]
Lars voted for: `git switch`

**Comment by richelbilderbeek** [comment]
I replaced all 'git checkout' by 'git switch' :+1:
