### ISSUE TITLE
[VoteD] all exercises are ideally part of implementing the project

### ISSUE THREAD

**Issue by LarsEklund** [UPPMAX/programming_formalisms#43]
Make all exercises part of implementing the project. including the TDD/Pair programming exercise maybe some sort of status function and movement function not necessarily OO but in a way that the learners can see what to implement once they start going into the simulation algorithms

**Comment by richelbilderbeek** [comment]
I agree!

**Comment by bclaremar** [comment]
I use some demos, as you know
Could it still be relevant to have this unrelated example? Otherwise demo in the project ruin their hands-on exercises in the project, I believe.
How to solve this otherwise?

**Comment by bclaremar** [comment]
But sure:
EXERCISES may probably be able to be project related

**Comment by richelbilderbeek** [comment]
> I use some demos, as you know
> Could it still be relevant to have this unrelated example? 
> Otherwise demo in the project ruin their hands-on exercises in the project, I believe.
> How to solve this otherwise

I enjoy the thoughtfulness of worrying of ruining their hands-on experience! I do think we should dare to remove unrelated examples and focus more strongly on the project. It would help us weed out content that is only nice-to-have, yet less relevant for the project.

**Comment by richelbilderbeek** [comment]
Sounds like this should be discussed @LarsEklund :-)

**Comment by richelbilderbeek** [comment]
The course content is what we use **and** alternatives. As we need discuss alternatives besides the course content, by definition, all exercises **cannot** be part of the project.

Our main/project exercises should ideally be part of implementing the project and/or follow the workflow.

We all agree with this statement!
