### ISSUE TITLE
Pick course dates autumn 2024

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#46]
We need to pick the course dates for autumn 2024.

As far as I can conclude, autumn 2023 was is week 48, nov 27-dec 1.

These are the possible weeks:

- Oct 1-Oct 5, week 40: NAISS user forum from Oct 1-3
- Oct 7-Oct 11, week 41: NBIS retreat from Oct 7-10
- Oct 14-Oct 18, week 42: Singularity workshop on 16th
- Oct 21-Oct 25, week 43: R, Julia, Python, Matlab for HPC  course from Oct 22-25
- Oct 28-Nov 1: week 44: no events, Richel absent
- Nov 4-Nov 8: week 45: no events, Richel leaves Friday 15:00 
- Nov 11-Nov 15, week 46: RDA 23:rd plenary Costa Rica, 12-14 Nov
- **Nov 18-Nov 22, week 47: no events**
- **Nov 25-Nov 29, week 48: no events**
- Dec 2-Dec 6, week 49: no events
- Dec 9-Dec 13, week 50: no events, Richel leaves Friday 15:00

**Comment by LarsEklund** [comment]
47 or 48 looks promising this time around this year as well. lets compare with other NBIS courses and code refinery

**Comment by richelbilderbeek** [comment]
I can check the NBIS courses. In short: there is no conflict!

All dates:

- Nov 25-29
- Oct 14 - 18
- Sept 18-19
- **Nov 26 - 29**
- 28 Oct - 1 Nov
- September 16-20
- Nov 11-15
- **Nov 21-22**

Course names with Dates between Nov 18-Nov 29:

- week 48: Nov 26-29: Biomarker Discovery, Mun-Gwan and Prasoon Agarwal
- week 47: Nov 21-22: Advisory Program Grand Meeting, Anna Johansson, Diana Ekman

Of these, I'd say no course really conflict with us.

**Comment by richelbilderbeek** [comment]
CodeRefinery has nothing registerered yet at https://coderefinery.org/workshops/upcoming/

**Comment by richelbilderbeek** [comment]
Programming Formalisms will be in week 47, i.e. Monday 18th November to and including Friday 22nd November :+1:
