### ISSUE TITLE
Put meeting notes in GitHub, as voted for

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#47]
Currently, everything about this course is on this repo, except for the course meeting notes.

What about we put our meeting notes here too?

**Comment by richelbilderbeek** [comment]
I vote: yes

I assign the others, so they can cast their votes too.

**Comment by LarsEklund** [comment]
vote: yes

**Comment by bclaremar** [comment]
vote: yes

**Comment by richelbilderbeek** [comment]
Done!
