### ISSUE TITLE
Markdown link not rendered properly on index.html

### ISSUE THREAD

**Issue by dahlo** [UPPMAX/programming_formalisms#5]
![image](https://github.com/UPPMAX/programming_formalisms/assets/1188623/22aaa14a-430a-44ae-819d-040c46df7e9d)

**Comment by richelbilderbeek** [comment]
@dahlo which URL is that taken from? I took a quick look and failed finding it :-/

**Comment by dahlo** [comment]
Huh, it was from https://uppmax.github.io/programming_formalisms_intro/index.html but now it has rendered correctly. Must have been temporary.
