### ISSUE TITLE
[DECIDED] Giving advice means a reference to the literature? Try to, you are not forced to]

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#57]
What do we think about giving advice (e.g. 'Always do X') without a reference to the literature?

To reason is because I want to be able to say 'The course teaches evidence-based best practices backed by the literature', instead of 'Some parts of the course teaches [that]'.

Could we commit to this yes/no?

My vote is a **yes**: I think most of our advice should be backed up by a reference to the literature, to prevent teaching what we do, but teach what one should do instead.

**Comment by richelbilderbeek** [comment]
> Is there literature for everything?

Yes, for everything that is important there is.

> Where to draw the line?

I'd say books and academic papers :+1:

**Comment by QuantumTwitch** [comment]
Why is a blog post considered more valuable than our own experience, a blogpost in nothing more than another persons unbacked (drawn from personal experience) opinion. Blogposts have no more merit that our own opinions if we call it evidence based and backed by literature.

**Comment by QuantumTwitch** [comment]
Gwynet Paltrow has a lot of really influential blog post regarding biochemistry that are utter nonsense and have no evidence or backing in science ofthen contraticting known scientific facts.  Same goes for a lot of flatearthers and evolution deniers popularity and influence is not a good measure of content quality on the internet. (Not to say that you cant have great blogposts as a reference just that influence is not a good metric)

**Comment by richelbilderbeek** [comment]
@QuantumTwitch I agree with the point, thanks for convincing me on the uselessness of a blog post. To me, this now means that blog posts and personal opinions are useless, as, I repeat myself:

> I'd say the goal of this is to prevent us making things up and using formal practices as described elsewhere.

**Comment by richelbilderbeek** [comment]
It seems this rule is broken by our decision on what is course content ...?

I copy-paste from [https://uppmax.github.io/programming_formalisms/intro/](https://uppmax.github.io/programming_formalisms/intro/):

- [Only what is used by the student project is course content, with alternatives relevant to academics provided in lecture (or extra material) to what we do](https://github.com/UPPMAX/programming_formalisms/issues/52).

**Comment by richelbilderbeek** [comment]
On [20240926](https://github.com/UPPMAX/programming_formalisms/blob/main/meeting_notes/20240926.md) we reached the decision: 

  - We think it is a good idea to increase the amount of references to the literature, but do not force teachers to do so
