### ISSUE TITLE
Content and order: BC's questions

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/programming_formalisms#65]
Class diagrams:
- last time: Tue morning 
- this year: Thursday, Richel: class design?

Project page (Tue morning, Richel)
- is that README file?

Pair-programming (using class diagrams)
- When do you do that?
- Included in TDD?

CI = GitHub workflows?

**Comment by richelbilderbeek** [comment]
- Class diagrams:
  - last time: Tue morning
  - this year: Thursday, Richel: class design?
    - RB: unsure
- Project page (Tue morning, Richel)
  - is that README file?
    - RB: not yet
- Pair-programming (using class diagrams)
  - When do you do that?
    - RB: Maybe Thursday
  - Included in TDD?
    - RB: yes, I will do TDD :-)

**Comment by LarsEklund** [comment]
I belive I am doing class design. on Thursday, we are just going to do a more simplefied approach that is more practical but still showcases the consepts.
