### ISSUE TITLE
Wednesday git: BC/RB discuss integration with project

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/programming_formalisms#66]

**Comment by richelbilderbeek** [comment]
Fun! 

Here are the workflows I will use

- Basic git workflow: https://youtu.be/vPyHWsnbXw8
- Work on topic branch, merge using GitHub interface: https://youtu.be/vPyHWsnbXw8
- Work on topic branch, merge with code review: https://youtu.be/pM520_JLR6w

**Comment by richelbilderbeek** [comment]
What about we discuss this Tuesday? Any time will work for me

**Comment by bclaremar** [comment]
14.00

**Comment by bclaremar** [comment]
same room
