### ISSUE TITLE
Check for spelling in 'DevelopmentDesign' folder

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#7]
Currently, there are spelling errors in the 'DevelopmentDesign' folder.

As priorities are not on fixing these spelling errors now, [this commit](https://github.com/UPPMAX/programming_formalisms/commit/3763d6e2834759e923a540254bc54895b3780487) excludes the folder from a spell check.

When spelling checking is desired again, that folder can be added again :-)

**Comment by LarsEklund** [comment]
Most of the spelling has been fixed. With some probably remaining, the Markdown is also linted except for MD033

**Comment by richelbilderbeek** [comment]
Well done @LarsEklund! Closing this Issue :-)
