### ISSUE TITLE
Just two problematic links left

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/programming_formalisms#70]
[✖] https://github.com/carpentries-incubator/managing-computational-projects/blob/gh-pages/_episodes/09-codereview.md → Status: 404

Can it be replaced by this one? 
https://carpentries-incubator.github.io/managing-computational-projects/13-codereview.html 

[✖] https://zenodo.org/api/iiif/v2/5c8c70c9-4119-4917-91d1-bc955943f586:328322b3-ab2f-43c8-a4ba-eb6e11d48ac0:reusable-code-garden-with-text.jpg/full/750,/0/default.jpg → Status: 404

**Comment by bclaremar** [comment]
The other one is  the image 
![Garden of code](https://zenodo.org/api/iiif/v2/5c8c70c9-4119-4917-91d1-bc955943f586:328322b3-ab2f-43c8-a4ba-eb6e11d48ac0:reusable-code-garden-with-text.jpg/full/750,/0/default.jpg)"

**Comment by richelbilderbeek** [comment]
Links are not mine, I thought they were yours? If not, I suggest to remove them, as nobody benefits from fixing these :+1:

**Comment by bclaremar** [comment]
It was Jon's.
Placed in ./common practices

**Comment by bclaremar** [comment]
removed links
